_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 65
DATASETS:
  TRAIN: ("coco_2017_ovd_all_train",)
  TEST: ("coco_2017_ovd_all_test",)