_BASE_: "./CLIP_fast_rcnn_R_50_C4.yaml"
MODEL:
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 1203
    NMS_THRESH_TEST: 0.3
  CLIP:
    NO_BOX_DELTA: True
    OFFLINE_RPN_NMS_THRESH: 0.9
    VIS: True # Note: visualize the scores before multiplying RPN scores, if any
DATASETS:
  TRAIN: ("lvis_v1_train_custom_img",)
  TEST: ("lvis_v1_val_custom_img",)